config/routes.rb
Rails.application.routes.draw do
  resources :payment_transactions, only: %w(index)
  resources :merchants
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :payment_transactions, only: %w(index create)
    end
  end
end

app/models/merchant.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  api_key                :string
#  description            :text
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  status                 :string           default("inactive")
#  total_transaction_sum  :float
#  type                   :string           default("Merchant")
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_api_key               (api_key) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_status                (status)
#  index_users_on_type                  (type)
#
class Merchant < User
  before_save :set_api_key

  has_many :payment_transactions, dependent: :destroy

  %w(active inactive).each do |merchant_status|
    define_method("is_#{merchant_status.downcase}?") do
      status == merchant_status
    end
  end

  private

  def set_api_key
    self.api_key = SecureRandom.hex if api_key.blank?
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: %w(show edit update destroy)

  def show; end

  def index
    @merchants = MerchantsService.call(params)
  end

  def edit
    @form = MerchantForm.new(@merchant)
  end

  def update
    @form = MerchantForm.new(@merchant, merchant_form_params)
    if @form.update
      redirect_to merchants_path, notice: 'Merchant updated'
    else
      flash[:alert] = @merchant.errors.full_messages[0]
      redirect_to(edit_merchant_path(@merchant))
    end
  end

  def destroy
    alert_msg = 'Merchant cannot be deleted because they have transactions'

    if @merchant.payment_transactions.blank?
      @merchant.destroy
      alert_msg = 'Merchant was successfully deleted'
    end

    respond_to do |format|
      format.html { redirect_to merchants_url, alert: alert_msg }
      format.json { head :no_content }
    end
  end

  private

  def set_merchant
    @merchant = Merchant.find(params[:id])
  end

  def merchant_form_params
    params.require(:merchant_form).permit(:name, :email, :description)
  end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_merchant_row.html.slim
tr
  td
    == link_to(merchant.name, merchant)
  td
    == merchant.email
  td
    == merchant.description
  td style = 'text-align: center;'
    == merchant.total_transaction_sum.to_f
  td
    .btn-group[role="group" aria-label="Basic example"]
      = link_to('Edit', edit_merchant_path(merchant), class: 'btn btn-outline-success')
      = link_to('Delete', merchant, data: {method: 'delete', confirm: 'Are you sure you want to delete this merchant?'}, class: 'delete_merchant btn btn-outline-danger')

app/views/merchants/edit.html.slim
h3 Edit Merchant
br

= form_for @form, url: merchant_path(@merchant), method: 'PUT' do |f|
  div.form-group
  	label Name
  	= f.text_field :name, value: @merchant.name, id: 'name', class: 'form-control'

  br
  div.form-group
  	label Email
  	= f.text_field :email, value: @merchant.email, class: 'form-control'

  br
  div.form-group
  	label Description
  	= f.text_area :description, value: @merchant.description, class: 'form-control'

  br
  = f.submit 'Update', class: 'btn btn-success'

app/views/merchants/index.html.slim
h1 Merchants
hr
br
table.table.table-striped.table-hover
	thead
	  tr
	    th[scope="col"]
	      | Name
	    th[scope="col"]
	      | Email
	    th[scope="col"]
	      | Description
	    th[scope="col"]
	      | Total Transactions
	    th[scope="col"]
	tbody
		- @merchants.find_each do |merchant|
			== render partial: 'merchants/merchant_row', locals: {merchant: merchant}

app/views/merchants/show.html.slim
.card
  h5.card-header
    == @merchant.name
  .card-body
    h5.card-title
      == @merchant.email
    p.card-text
      == @merchant.description
    button.btn.btn-outline-primary[type="button"]
      |  Total Transactions 
      span.badge.bg-success
        == @merchant.total_transaction_sum.to_f

br

.card
  h5.card-header
    | Transactions
  .card-body
    table.table.table-striped.table-hover
    	thead
    	  tr
    	    th[scope="col"]
    	      | Customer Email
    	    th[scope="col"]
    	      | Customer Phone
    	    th[scope="col"]
    	      | Amount
    	    th[scope="col"]
    	      | Status
    	    th[scope="col"]
    	    	| Merchant
    	tbody
    		- @merchant.payment_transactions.find_each do |payment_transaction|
    			== render partial: 'payment_transactions/payment_transaction_row', locals: {payment_transaction: payment_transaction}